# Discord Bot設定
discord:
  token: "YOUR_DISCORD_BOT_TOKEN_HERE"
  # 初期監視チャンネルID（複数可）
  channels:
    - 123456789012345678
    - 987654321098765432
  # 起動時に取得する過去メッセージ数
  history_limit: 50
  # メモリに保持する最大メッセージ数
  max_messages: 100

# WebSocketサーバー設定
websocket:
  host: "0.0.0.0"
  port: 8765

# ログ設定
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
